### ISSUE TITLE
Undefined method "pid" for FlyingSphinxController

### ISSUE THREAD

**Issue by ethizedo** [flying-sphinx/flying-sphinx#20]
Hi, 

My search on my website works for some request, and doesn't work for others (without any error). When I try "rake Ts:rebuild", I get the following error : 

```
NoMethodError: undefined method `pid' for #<FlyingSphinx::Controller:0x000055cbd5199e60>
/app/vendor/bundle/ruby/2.6.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/rake_interface.rb:79:in `stop'
/app/vendor/bundle/ruby/2.6.0/gems/thinking-sphinx-3.3.0/lib/thinking_sphinx/tasks.rb:44:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/2.6.0/gems/airbrake-9.1.0/lib/airbrake/rake.rb:17:in `execute'
/app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
```

Do you know where it can come from ? Thanks a lot !

Marion

**Comment by pat** [comment]
Hi Marion,

To use the standard `ts` rake tasks with Flying Sphinx, you'll need to make sure you're using a 4.x release of Thinking Sphinx (and ideally, the latest Flying Sphinx release as well). Prior to 4.x, Flying Sphinx had its own `fs` prefixed tasks instead (e.g. `fs:rebuild`) - but if you're already using the latest Flying Sphinx, then those tasks won't be available.

In terms of upgrading, from your stack trace it seems you're using TS v3.3.0 - the only breaking change I can think of is the removal of auto-typed search filter values. This is mentioned in both the [3.4.0 release notes](https://github.com/pat/thinking-sphinx/releases/tag/v3.4.0) (when it was deprecated) and [4.0.0 release notes](https://github.com/pat/thinking-sphinx/releases/tag/v4.0.0) (when it was removed). Support for old Ruby versions was also removed, but you're on 2.6, so that's not a problem.

Beyond that, I don't think anything else should stop you from upgrading all the way through to v4.4.1! But do let me know if you've any questions.

**Comment by ethizedo** [comment]
Thanks, the upgrade solved the problem !!
